environment: development
chdir: /var/www/simple-ruby-facebook-example
address: 127.0.0.1
user: www-data
group: www-data
port: 14000
pid: /var/www/simple-ruby-facebook-example/thin.pid
rackup: /var/www/simple-ruby-facebook-example/config.ru
log: /var/www/simple-ruby-facebook-example/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true

